Style/IndentationConsistency:
  EnforcedStyle: rails

Metrics/LineLength:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
